{% set version = '3.17' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeva
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modEvA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modEvA/modEvA_{{ version }}.tar.gz
  sha256: f27ba3da0bbbb61d57e188cbfdf1804d412b8ba256ddfa5fef7da261e5d8f3b0

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-terra >1.5_50
  run:
    - r-base
    - r-terra >1.5_50

test:
  commands:
    - $R -e "library('modEvA')"           # [not win]
    - "\"%R%\" -e \"library('modEvA')\""  # [win]

about:
  home: http://modeva.r-forge.r-project.org/
  license: GPL-3.0-only
  summary: Analyses species distribution models and evaluates their performance. It includes
    functions for variation partitioning, extracting variable importance, computing
    several metrics of model discrimination and calibration performance, optimizing
    prediction thresholds based on a number of criteria, performing multivariate environmental
    similarity surface (MESS) analysis, and displaying various analytical plots. Initially
    described in Barbosa et al. (2013) <doi:10.1111/ddi.12100>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: modEvA
# Type: Package
# Title: Model Evaluation and Analysis
# Version: 3.17
# Date: 2024-06-06
# Author: Barbosa A.M., Brown J.A., Jimenez-Valverde A., Real R.
# Maintainer: A. Marcia Barbosa <ana.marcia.barbosa@gmail.com>
# Imports: graphics, grDevices, stats, methods, terra (> 1.5-50)
# Description: Analyses species distribution models and evaluates their performance. It includes functions for variation partitioning, extracting variable importance, computing several metrics of model discrimination and calibration performance, optimizing prediction thresholds based on a number of criteria, performing multivariate environmental similarity surface (MESS) analysis, and displaying various analytical plots. Initially described in Barbosa et al. (2013) <doi:10.1111/ddi.12100>.
# LazyLoad: yes
# LazyData: yes
# License: GPL-3
# URL: http://modeva.r-forge.r-project.org/
# NeedsCompilation: no
# Packaged: 2024-06-06 10:58:51 UTC; marcia
# Depends: R (>= 2.10)
# Repository: CRAN
# Date/Publication: 2024-06-06 11:50:07 UTC
